apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-deployment
  labels:
    app: service-three
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        #image: nginx:1.7.9
        image: rubendario/service3
        ports:
        - containerPort: 8080

